version: '3.8'

services:
  scraper-vps:
    build: .
    container_name: scraper_vps
    volumes:
      # Mapujemy obecny katalog, żeby plik CSV pojawił się na dysku VPSa
      - .:/app
    environment:
      # TUTAJ DEFINIUJESZ WARUNKI DLA VPS:
      - MAX_EXECUTION_TIME=21600       # 6 godzin
      - OUTPUT_FILE=mieszkania_vps.csv # Osobny plik!
      - TZ=Europe/Warsaw # Ustaw strefę czasową, żeby logi miały poprawne znaczniki czasu
    # Opcjonalnie: restartuj kontener tylko ręcznie (nie chcemy pętli nieskończonej w tle)
    restart: "no"