name: Scraper - GitHub Actions (Short Run)

on:
  schedule:
    - cron: '0 8,20 * * *' # Codziennie 8:00 rano i 20:00 wieczorem
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Pozwala botowi zapisać plik w repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t scraper .

      - name: Run Scraper
        env:
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        # TUTAJ DEFINIUJESZ WARUNKI DLA GITHUB ACTIONS:
        run: |
          if [ -z "${DISCORD_URL:-}" ]; then
            echo "❌ DISCORD_URL is empty in GitHub Actions"
            exit 1
          fi

          docker run --rm \
          -e MAX_EXECUTION_TIME=1500 \
          -e MAX_PAGES=5 \
          -e OUTPUT_FILE="mieszkania_gh.csv" \
          -e DISCORD_URL="${DISCORD_URL}" \
          -v ${{ github.workspace }}:/app \
          scraper

      - name: Commit & Push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Dodajemy plik z danymi oraz log runu do readme.md
          git add mieszkania_gh.csv
          [ -f readme.md ] && git add readme.md
          git commit -m "Auto-update danych z GitHub Actions $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "Brak zmian"
          git pull --rebase origin main
          git push
